-- ========================================
-- E-Commerce Database Schema
-- Includes: Tables, Indexes, Triggers
-- Author: Generated by ChatGPT
-- ========================================

Below is the sql server schema ecommerce application. I am planning to use this schema in microservices architecture. Please update the code with necessary changes
-- ===================
-- Users Table
-- ===================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Users]') AND type in (N'U'))
BEGIN
    CREATE TABLE Users (
        UserId INT IDENTITY(1,1) PRIMARY KEY,
        Name NVARCHAR(100),
        Email NVARCHAR(100) UNIQUE,
        PasswordHash NVARCHAR(255),
        Address NVARCHAR(255),
        Phone NVARCHAR(20),
        CreatedAt DATETIME2 DEFAULT GETDATE(),
        ModifiedAt DATETIME2 DEFAULT GETDATE()
    );
END

-- ===================
-- Products Table
-- ===================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Products]') AND type in (N'U'))
BEGIN
    CREATE TABLE Products (
        ProductId INT IDENTITY(1,1) PRIMARY KEY,
        Name NVARCHAR(100),
        Description NVARCHAR(MAX),
        Price DECIMAL(10,2),
        Stock INT,
        Category NVARCHAR(100),
        ImageUrl NVARCHAR(255),
        CreatedAt DATETIME2 DEFAULT GETDATE(),
        ModifiedAt DATETIME2 DEFAULT GETDATE()
    );
END

-- ===================
-- OrderStatus Table
-- ===================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OrderStatus]') AND type in (N'U'))
BEGIN
    CREATE TABLE OrderStatus (
        StatusId INT IDENTITY(1,1) PRIMARY KEY,
        StatusName NVARCHAR(50),
        CreatedAt DATETIME2 DEFAULT GETDATE(),
        ModifiedAt DATETIME2 DEFAULT GETDATE()
    );
END

-- ===================
-- Orders Table
-- ===================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Orders]') AND type in (N'U'))
BEGIN
    CREATE TABLE Orders (
        OrderId INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT,
        StatusId INT,
        OrderDate DATETIME2 DEFAULT GETDATE(),
        TotalAmount DECIMAL(10,2),
        CreatedAt DATETIME2 DEFAULT GETDATE(),
        ModifiedAt DATETIME2 DEFAULT GETDATE(),
        FOREIGN KEY (UserId) REFERENCES Users(UserId),
        FOREIGN KEY (StatusId) REFERENCES OrderStatus(StatusId)
    );
END

-- ===================
-- OrderItems Table
-- ===================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[OrderItems]') AND type in (N'U'))
BEGIN
    CREATE TABLE OrderItems (
        OrderItemId INT IDENTITY(1,1) PRIMARY KEY,
        OrderId INT,
        ProductId INT,
        Quantity INT,
        Price DECIMAL(10,2),
        CreatedAt DATETIME2 DEFAULT GETDATE(),
        ModifiedAt DATETIME2 DEFAULT GETDATE(),
        FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
        FOREIGN KEY (ProductId) REFERENCES Products(ProductId)
    );
END

-- ===================
-- Reviews Table
-- ===================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Reviews]') AND type in (N'U'))
BEGIN
    CREATE TABLE Reviews (
        ReviewId INT IDENTITY(1,1) PRIMARY KEY,
        UserId INT,
        ProductId INT,
        Rating INT,
        Comment NVARCHAR(MAX),
        CreatedAt DATETIME2 DEFAULT GETDATE(),
        ModifiedAt DATETIME2 DEFAULT GETDATE(),
        FOREIGN KEY (UserId) REFERENCES Users(UserId),
        FOREIGN KEY (ProductId) REFERENCES Products(ProductId)
    );
END

-- =============================
-- PaymentMethodTypes Table
-- =============================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PaymentMethodTypes]') AND type in (N'U'))
BEGIN
    CREATE TABLE PaymentMethodTypes (
        PaymentMethodTypeId INT IDENTITY(1,1) PRIMARY KEY,
        MethodName NVARCHAR(50),
        CreatedAt DATETIME2 DEFAULT GETDATE(),
        ModifiedAt DATETIME2 DEFAULT GETDATE()
    );
END

-- ===================
-- Payments Table
-- ===================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Payments]') AND type in (N'U'))
BEGIN
    CREATE TABLE Payments (
        PaymentId INT IDENTITY(1,1) PRIMARY KEY,
        OrderId INT,
        PaymentMethodTypeId INT,
        PaymentDate DATETIME2,
        Amount DECIMAL(10,2),
        PaymentStatus NVARCHAR(50),
        CreatedAt DATETIME2 DEFAULT GETDATE(),
        ModifiedAt DATETIME2 DEFAULT GETDATE(),
        FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
        FOREIGN KEY (PaymentMethodTypeId) REFERENCES PaymentMethodTypes(PaymentMethodTypeId)
    );
END

-- ===================
-- CartItems Table
-- ===================
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CartItems]') AND type in (N'U'))
BEGIN
    CREATE TABLE CartItems (
        CartItemID INT IDENTITY(1,1) PRIMARY KEY,
        UserID INT NULL,
        SessionID VARCHAR(100) NULL,
        ProductID INT NOT NULL,
        Quantity INT NOT NULL CHECK (Quantity > 0),
        CreatedAt DATETIME DEFAULT GETDATE(),
        ModifiedAt DATETIME DEFAULT GETDATE(),
        FOREIGN KEY (UserID) REFERENCES Users(UserID),
        FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
    );
END

-- ===================
-- Triggers
-- ===================
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE name = 'trg_Update_CartItems_ModifiedAt')
BEGIN
    EXEC('CREATE TRIGGER trg_Update_CartItems_ModifiedAt
    ON CartItems
    AFTER UPDATE
    AS
    BEGIN
        SET NOCOUNT ON;
        UPDATE CartItems
        SET ModifiedAt = GETDATE()
        FROM CartItems c
        INNER JOIN inserted i ON c.CartItemID = i.CartItemID;
    END');
END

-- ===================
-- Indexes for Optimization
-- ===================
-- Products table indexes
IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Products_Name' AND object_id = OBJECT_ID('Products')
)
CREATE NONCLUSTERED INDEX IX_Products_Name ON Products(Name);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Products_Category' AND object_id = OBJECT_ID('Products')
)
CREATE NONCLUSTERED INDEX IX_Products_Category ON Products(Category);

-- Orders table indexes
IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Orders_UserId' AND object_id = OBJECT_ID('Orders')
)
CREATE NONCLUSTERED INDEX IX_Orders_UserId ON Orders(UserId);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Orders_StatusId' AND object_id = OBJECT_ID('Orders')
)
CREATE NONCLUSTERED INDEX IX_Orders_StatusId ON Orders(StatusId);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Orders_OrderDate' AND object_id = OBJECT_ID('Orders')
)
CREATE NONCLUSTERED INDEX IX_Orders_OrderDate ON Orders(OrderDate);

-- OrderItems table indexes
IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_OrderItems_OrderId' AND object_id = OBJECT_ID('OrderItems')
)
CREATE NONCLUSTERED INDEX IX_OrderItems_OrderId ON OrderItems(OrderId);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_OrderItems_ProductId' AND object_id = OBJECT_ID('OrderItems')
)
CREATE NONCLUSTERED INDEX IX_OrderItems_ProductId ON OrderItems(ProductId);

-- Reviews table indexes
IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Reviews_UserId' AND object_id = OBJECT_ID('Reviews')
)
CREATE NONCLUSTERED INDEX IX_Reviews_UserId ON Reviews(UserId);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Reviews_ProductId' AND object_id = OBJECT_ID('Reviews')
)
CREATE NONCLUSTERED INDEX IX_Reviews_ProductId ON Reviews(ProductId);

-- Payments table indexes
IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Payments_OrderId' AND object_id = OBJECT_ID('Payments')
)
CREATE NONCLUSTERED INDEX IX_Payments_OrderId ON Payments(OrderId);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Payments_PaymentMethodTypeId' AND object_id = OBJECT_ID('Payments')
)
CREATE NONCLUSTERED INDEX IX_Payments_PaymentMethodTypeId ON Payments(PaymentMethodTypeId);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Payments_PaymentStatus' AND object_id = OBJECT_ID('Payments')
)
CREATE NONCLUSTERED INDEX IX_Payments_PaymentStatus ON Payments(PaymentStatus);

-- CartItems table indexes
IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_CartItems_UserId' AND object_id = OBJECT_ID('CartItems')
)
CREATE NONCLUSTERED INDEX IX_CartItems_UserId ON CartItems(UserID);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_CartItems_SessionId' AND object_id = OBJECT_ID('CartItems')
)
CREATE NONCLUSTERED INDEX IX_CartItems_SessionId ON CartItems(SessionID);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_CartItems_ProductId' AND object_id = OBJECT_ID('CartItems')
)
CREATE NONCLUSTERED INDEX IX_CartItems_ProductId ON CartItems(ProductID);

IF NOT EXISTS (
    SELECT * FROM sys.indexes WHERE name = 'IX_Orders_UserId_StatusId' AND object_id = OBJECT_ID('Orders')
)
CREATE NONCLUSTERED INDEX IX_Orders_UserId_StatusId ON Orders(UserId, StatusId);

